spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.fengdai.org:3306/app_version_manager_open_source?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: csp
    password: csp2017DEV9
  redis:
    host: localhost
    port: 6379
    database: 0
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 1
      min-idle: 0

server:
  port: 8087

csp:
  sdk:
    basic:
      host: uat-ucenter.tairancloud.com
      url: http://uat-ucenter.tairancloud.com/gateway
      app-id: uc2a962fb13fc3c33a
      app-secret: 5ca38c4ab6574bcd8d0844d41b05413e